version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map host:container
    container_name: react-app-container
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
